POST http://127.0.0.1:5000/addresses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NzI4NDI3NzF9.uygOxSPo0qLmQdgg-AaJTctdXLCeQQzSAmkRMa7llys
{
  "receiver_name": "Nguyen Van B",
  "phone": "0123456789",
  "address_line": "456 Tran Phu",
  "ward": "Hai Chau 4",
  "district": "Hai Chau",
  "city": "Da Nang",
  "is_default": true
}
### get http://
GET http://127.0.0.1:5000/addresses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NzI4OTU1OTV9.GtM4eR1-jl8_w5_Sr3NntathqOsAgEnwN9fzjIQ977w