POST http://127.0.0.1:5000/categories
Content-Type: application/json
Authorization: Bearer 
{
  "name": "Trứng",
  "description": "Các loại trứng tươi ngon, giàu dinh dưỡng, được đóng gói trong hộp tiện lợi, bảo quản tốt.",
  "image": "/uploads/trung-cut.png"
}

### lấy tất cả
GET http://127.0.0.1:5000/categories

### lấy từng cái theo_id
GET http://127.0.0.1:5000/categories/3


