POST http://127.0.0.1:5000/product-images
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NzI2MjkxMDB9.fO0XMlUGXZzm-uq7HZOe6ADiYFrKCwrSCzqjc8qgZyI

{
  "product_id": 3,
  "image_url": "/uploads/Screenshot_2025-11-12_012015.jpg",
  "is_main": true
}
###
GET http://127.0.0.1:5000/product-images/product/1
###
GET http://127.0.0.1:5000/uploads/OIP2.jpg
###

 