POST http://127.0.0.1:5000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NzI3NzIyNjJ9.b0s6gevOKuhC6_zJuAp1kn2brQrtCoplsSdXL19CruM

{
  "name": "Trứng gà ta hộp 6 quả từ 180g-210g",
  "description": "Trứng gà ta hộp 6 quả từ 180g-210g là sản phẩm trứng gà được đóng gói trong hộp chứa 6 quả...",
  "price": 27000,
  "manufacture_date": "2026-02-24",
  "expiry_date": "2026-03-24",
  "origin": "Việt Nam",
  "unit": "Hộp",
  "category_id": 1,
  "supplier_id": 1
}
###
PUT http://127.0.0.1:5000/products/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NzI3NzIyNjJ9.b0s6gevOKuhC6_zJuAp1kn2brQrtCoplsSdXL19CruM

{
  "name": "Tr-210g"
}
###
GET http://127.0.0.1:5000/products
### 
GET http://127.0.0.1:5000/products/
### lấy sản phẩm theeo category_id(mục lục)
GET http://127.0.0.1:5000/products/2

###
DELETE  http://127.0.0.1:5000/products/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NzI3MjQyMDB9.wmhrcPoI6ZYump0zZRtR6ExN2Y4qM71miWdrUMyiYXI
